version: "3.9"

services:
  web:
    image: nginx:1.27-alpine
    container_name: landing-nginx-local
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./infra/nginx/default.local.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped
