services:
  landing:
    container_name: landing-dev
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/conf.d/landing.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/nginx/includes:/etc/nginx/includes:ro
