services:
  landing:
    container_name: landing
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/conf.d/landing.prod.https.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/certs:/etc/nginx/certs:ro
      - ./infra/nginx/includes:/etc/nginx/includes:ro
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3

