version: "3.9"

services:
  web:
    image: nginx:1.27-alpine
    container_name: landing-nginx
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./infra/nginx:/etc/nginx/conf.d:ro
      - ./infra/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
